"! <p class="shorttext">JSON2ABAPType visualized with abap2UI5</p>
"!
"! Paste a JSON document and get the ABAP TYPES that hold it, generated by
"! https://github.com/fidley/JSON2ABAPType. The library has no global class
"! for the type generation: it ships ZUI2_JSON (a copy of /UI2/CL_JSON with
"! GENERATE) and the report ZJSON2ABAPTYPE, whose local class
"! LCL_JSON_STRUCTURE turns the generated data reference into TYPES. This
"! app calls ZUI2_JSON=>GENERATE statically and creates LCL_JSON_STRUCTURE
"! dynamically through its absolute name (\PROGRAM=ZJSON2ABAPTYPE\CLASS=...),
"! so both halves run as the library ships them - nothing is copied.
"!
"! Read-only: nothing is stored and no business data is read. The optional
"! formatting step calls the standard function module PRETTY_PRINTER on the
"! generated text only, as the report does.
CLASS z2ui5_cl_osl_json2type DEFINITION PUBLIC.

  PUBLIC SECTION.
    INTERFACES z2ui5_if_app.

    TYPES:
      BEGIN OF ty_s_key_text,
        key  TYPE string,
        text TYPE string,
      END OF ty_s_key_text.
    TYPES ty_t_key_text TYPE STANDARD TABLE OF ty_s_key_text WITH EMPTY KEY.

    TYPES:
      BEGIN OF ty_s_mapping,
        json TYPE string,
        abap TYPE string,
      END OF ty_s_mapping.
    TYPES ty_t_mapping TYPE STANDARD TABLE OF ty_s_mapping WITH EMPTY KEY.

    TYPES:
      BEGIN OF ty_s_node,
        level      TYPE i,
        name       TYPE string,
        kind       TYPE string,
        state      TYPE string,
        type_kind  TYPE string,
        component  TYPE string,
      END OF ty_s_node.
    TYPES ty_t_node TYPE STANDARD TABLE OF ty_s_node WITH EMPTY KEY.

    DATA tab          TYPE string.
    DATA json         TYPE string.
    DATA naming       TYPE string.
    DATA pretty_print TYPE abap_bool.
    DATA types        TYPE string.
    DATA summary      TYPE string.
    DATA t_namings    TYPE ty_t_key_text.
    DATA t_mappings   TYPE ty_t_mapping.
    DATA t_nodes      TYPE ty_t_node.

  PROTECTED SECTION.
    TYPES:
      BEGIN OF ty_s_hierarchy,
        level           TYPE i,
        name            TYPE string,
        table           TYPE abap_bool,
        structure       TYPE abap_bool,
        type            TYPE string,
        length          TYPE i,
        decimals        TYPE i,
        final_type      TYPE string,
        type_definition TYPE string,
        id              TYPE i,
      END OF ty_s_hierarchy.
    TYPES ty_t_hierarchy TYPE STANDARD TABLE OF ty_s_hierarchy WITH EMPTY KEY.

    TYPES:
      BEGIN OF ty_s_source,
        line TYPE c LENGTH 255,
      END OF ty_s_source.
    TYPES ty_t_source TYPE STANDARD TABLE OF ty_s_source WITH EMPTY KEY.

    " the type generator is a local class of the library's report
    CONSTANTS c_converter TYPE string VALUE `\PROGRAM=ZJSON2ABAPTYPE\CLASS=LCL_JSON_STRUCTURE`.
    CONSTANTS c_build     TYPE string VALUE `BUILD_STRUCTURE`.
    CONSTANTS c_hierarchy TYPE string VALUE `HIERARCHY`.

    DATA client TYPE REF TO z2ui5_if_client.

    METHODS view_display.
    METHODS view_input
      IMPORTING
        parent TYPE REF TO z2ui5_cl_ui5_view_builder.
    METHODS view_output
      IMPORTING
        parent TYPE REF TO z2ui5_cl_ui5_view_builder.

    METHODS on_event.
    METHODS model_init.
    METHODS example_set.
    METHODS types_generate.
    METHODS pretty_mode
      RETURNING
        VALUE(result) TYPE zui2_json=>pretty_name_mode.
    METHODS name_mappings
      RETURNING
        VALUE(result) TYPE zui2_json=>name_mappings.
    METHODS nodes_set
      IMPORTING
        hierarchy TYPE ty_t_hierarchy.
    METHODS pretty_printer
      IMPORTING
        val           TYPE string
      RETURNING
        VALUE(result) TYPE string.

  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_osl_json2type IMPLEMENTATION.

  METHOD z2ui5_if_app~main.

    me->client = client.
    IF client->check_on_init( ).
      model_init( ).
      view_display( ).
    ELSEIF client->check_on_navigated( ).
      view_display( ).
    ELSEIF client->check_on_event( ).
      on_event( ).
    ENDIF.

  ENDMETHOD.


  METHOD view_display.

    DATA(page) = z2ui5_cl_ui5_view_builder=>factory(
        )->ele( n = `View` ns = `mvc`
            )->a( n = `displayBlock`  v = `true`
            )->a( n = `height`        v = `100%`
            )->a( n = `xmlns`         v = `sap.m`
            )->a( n = `xmlns:mvc`     v = `sap.ui.core.mvc`
            )->a( n = `xmlns:core`    v = `sap.ui.core`
            )->a( n = `xmlns:l`       v = `sap.ui.layout`
            )->a( n = `xmlns:editor`  v = `sap.ui.codeeditor`
            )->ele( `Shell`
                )->a( n = `appWidthLimited` v = `false`
                )->ele( `Page`
                    )->a( n = `title`          v = `JSON to ABAP types - JSON2ABAPType x abap2UI5`
                    )->a( n = `showNavButton`  b = client->check_app_prev_stack( )
                    )->a( n = `navButtonPress` v = client->_event_nav_app_leave( ) ).

    page->ele( `headerContent`
        )->tag( `Link`
            )->a( n = `text`   v = `fidley/JSON2ABAPType`
            )->a( n = `href`   v = `https://github.com/fidley/JSON2ABAPType`
            )->a( n = `target` v = `_blank` ).

    DATA(content) = page->ele( `content` ).

    content->ele( `OverflowToolbar`
        )->ele( `content`
            )->tag( `Label`
                )->a( n = `text` v = `Component names`
            )->ele( `Select`
                )->a( n = `selectedKey` v = client->_bind( naming )
                )->a( n = `items`       v = client->_bind( t_namings )
                )->a( n = `change`      v = client->_event( `GENERATE` )
                )->tag( n = `Item` ns = `core`
                    )->a( n = `key`  v = `{KEY}`
                    )->a( n = `text` v = `{TEXT}`
            )->end(
            )->tag( `CheckBox`
                )->a( n = `text`     v = `Pretty printer`
                )->a( n = `selected` v = client->_bind( pretty_print )
                )->a( n = `select`   v = client->_event( `GENERATE` )
            )->tag( `ToolbarSpacer`
            )->tag( `Button`
                )->a( n = `text`  v = `Reset example`
                )->a( n = `icon`  v = `sap-icon://reset`
                )->a( n = `press` v = client->_event( `RESET` )
            )->tag( `Button`
                )->a( n = `text`  v = `Generate`
                )->a( n = `icon`  v = `sap-icon://process`
                )->a( n = `type`  v = `Emphasized`
                )->a( n = `press` v = client->_event( `GENERATE` ) ).

    DATA(grid) = content->ele( n = `Grid` ns = `l`
        )->a( n = `defaultSpan` v = `XL6 L6 M12 S12`
        )->a( n = `class`       v = `sapUiSmallMargin` ).

    view_input( grid ).
    view_output( grid ).

    client->view_display( page->stringify( ) ).

  ENDMETHOD.


  METHOD view_input.

    DATA(content) = parent->ele( `VBox` ).

    content->tag( `Title`
        )->a( n = `text`  v = `JSON`
        )->a( n = `class` v = `sapUiTinyMarginBottom`
        )->tag( n = `CodeEditor` ns = `editor`
            )->a( n = `value`  v = client->_bind( json )
            )->a( n = `type`   v = `json`
            )->a( n = `height` v = `420px` ).

    DATA(table) = content->ele( `Table`
        )->a( n = `items` v = client->_bind( t_mappings )
        )->a( n = `class` v = `sapUiSmallMarginTop`
        )->ele( `headerToolbar`
            )->ele( `Toolbar`
                )->ele( `content`
                    )->tag( `Title`
                        )->a( n = `text` v = `Name mappings (JSON name to ABAP component)`
                    )->tag( `ToolbarSpacer`
                    )->tag( `Button`
                        )->a( n = `icon`    v = `sap-icon://add`
                        )->a( n = `tooltip` v = `Add mapping`
                        )->a( n = `press`   v = client->_event( `MAPPING_ADD` )

                )->end(
            )->end(
        )->end( ).

    table->ele( `columns`
        )->ele( `Column`
            )->tag( `Text`
                )->a( n = `text` v = `JSON name`
        )->end(
        )->ele( `Column`
            )->tag( `Text`
                )->a( n = `text` v = `ABAP component`
        )->end(
        )->ele( `Column`
            )->a( n = `width` v = `4rem` ).

    table->ele( `items`
        )->ele( `ColumnListItem`
            )->ele( `cells`
                )->tag( `Input`
                    )->a( n = `value` v = `{JSON}`
                )->tag( `Input`
                    )->a( n = `value` v = `{ABAP}`
                )->tag( `Button`
                    )->a( n = `icon`    v = `sap-icon://delete`
                    )->a( n = `type`    v = `Transparent`
                    )->a( n = `tooltip` v = `Remove mapping`
                    )->a( n = `press`   v = client->_event( val = `MAPPING_DELETE`
                                                            arg = `${JSON}` ) ).

  ENDMETHOD.


  METHOD view_output.

    DATA(items) = parent->ele( `IconTabBar`
        )->a( n = `selectedKey` v = client->_bind( tab )
        )->a( n = `expandable`  v = `false`
        )->ele( `items` ).

    items->ele( `IconTabFilter`
        )->a( n = `key`  v = `TYPES`
        )->a( n = `text` v = `ABAP TYPES`
        )->a( n = `icon` v = `sap-icon://source-code`
        )->ele( `content`
            )->tag( n = `CodeEditor` ns = `editor`
                )->a( n = `value`    v = client->_bind( types )
                )->a( n = `type`     v = `abap`
                )->a( n = `editable` v = `false`
                )->a( n = `height`   v = `560px` ).

    DATA(content) = items->ele( `IconTabFilter`
        )->a( n = `key`  v = `NODES`
        )->a( n = `text` v = `Detected structure`
        )->a( n = `icon` v = `sap-icon://tree`
        )->ele( `content` ).

    content->tag( `MessageStrip`
        )->a( n = `text`     v = client->_bind( summary )
        )->a( n = `type`     v = `Information`
        )->a( n = `showIcon` v = `true`
        )->a( n = `class`    v = `sapUiSmallMarginBottom` ).

    DATA(table) = content->ele( `Table`
        )->a( n = `items` v = client->_bind( t_nodes ) ).

    table->ele( `columns`
        )->ele( `Column`
            )->a( n = `width` v = `4rem`
            )->tag( `Text`
                )->a( n = `text` v = `Level`
        )->end(
        )->ele( `Column`
            )->tag( `Text`
                )->a( n = `text` v = `Name`
        )->end(
        )->ele( `Column`
            )->tag( `Text`
                )->a( n = `text` v = `Kind`
        )->end(
        )->ele( `Column`
            )->a( n = `minScreenWidth` v = `Tablet`
            )->a( n = `demandPopin`    v = `true`
            )->tag( `Text`
                )->a( n = `text` v = `Type kind`
        )->end(
        )->ele( `Column`
            )->a( n = `minScreenWidth` v = `Tablet`
            )->a( n = `demandPopin`    v = `true`
            )->tag( `Text`
                )->a( n = `text` v = `Generated line` ).

    table->ele( `items`
        )->ele( `ColumnListItem`
            )->ele( `cells`
                )->tag( `ObjectNumber`
                    )->a( n = `number` v = `{LEVEL}`
                )->tag( `ObjectIdentifier`
                    )->a( n = `title` v = `{NAME}`
                )->tag( `ObjectStatus`
                    )->a( n = `text`  v = `{KIND}`
                    )->a( n = `state` v = `{STATE}`
                )->tag( `Text`
                    )->a( n = `text` v = `{TYPE_KIND}`
                )->tag( `Text`
                    )->a( n = `text` v = `{COMPONENT}` ).

  ENDMETHOD.


  METHOD on_event.

    CASE client->get_event( ).

      WHEN `GENERATE`.
        types_generate( ).

      WHEN `RESET`.
        example_set( ).
        types_generate( ).

      WHEN `MAPPING_ADD`.
        APPEND INITIAL LINE TO t_mappings.

      WHEN `MAPPING_DELETE`.
        DATA(name) = client->get_event_arg( ).
        DELETE t_mappings WHERE json = name.
        types_generate( ).

    ENDCASE.

  ENDMETHOD.


  METHOD model_init.

    tab    = `TYPES`.
    naming = `EXTENDED`.
    t_namings = VALUE #( ( key = `NONE`           text = `None - JSON name upper case` )
                         ( key = `LOW_CASE`       text = `Low case` )
                         ( key = `CAMEL_CASE`     text = `Camel case to snake case` )
                         ( key = `EXTENDED`       text = `Extended camel case (default)` )
                         ( key = `USER`           text = `User - name mappings only` )
                         ( key = `USER_LOW_CASE`  text = `User and low case` )
                         ( key = `CASE_SENSITIVE` text = `Case sensitive - _ before capitals` ) ).
    example_set( ).
    types_generate( ).

  ENDMETHOD.


  METHOD example_set.

    pretty_print = abap_true.
    t_mappings = VALUE #( ( json = `customerName` abap = `CUSTOMER` ) ).

    DATA(lines) = VALUE string_table(
        ( `{` )
        ( `  "orderId": 4711,` )
        ( `  "customerName": "ACME Corp.",` )
        ( `  "express": true,` )
        ( `  "totalAmount": 1299.95,` )
        ( `  "createdAt": "2026-09-29T10:15:00Z",` )
        ( `  "tags": [ "priority", "b2b" ],` )
        ( `  "shipTo": {` )
        ( `    "street": "Dietmar-Hopp-Allee 16",` )
        ( `    "city": "Walldorf",` )
        ( `    "geo": { "lat": 49.29, "lon": 8.64 }` )
        ( `  },` )
        ( `  "items": [` )
        ( `    { "position": 10, "material": "MAT-001", "quantity": 2, "price": 499.99 },` )
        ( `    { "position": 20, "material": "MAT-002", "quantity": 1, "price": 299.97 }` )
        ( `  ]` )
        ( `}` ) ).
    json = concat_lines_of( table = lines sep = cl_abap_char_utilities=>newline ).

  ENDMETHOD.


  METHOD types_generate.

    CLEAR: types, t_nodes, summary.

    DATA(start) = condense( val = json del = | \t\n\r| ).
    IF start IS INITIAL OR ( start(1) <> `{` AND start(1) <> `[` ).
      client->message_box_display( `Enter a JSON object or array.` ).
      RETURN.
    ENDIF.

    DATA(data) = zui2_json=>generate( json          = json
                                      pretty_name   = pretty_mode( )
                                      name_mappings = name_mappings( ) ).
    IF data IS NOT BOUND.
      client->message_box_display( `ZUI2_JSON=>GENERATE could not convert the JSON - is it valid?` ).
      RETURN.
    ENDIF.

    DATA converter TYPE REF TO object.
    DATA result TYPE string.
    FIELD-SYMBOLS <hierarchy> TYPE ANY TABLE.
    TRY.
        CREATE OBJECT converter TYPE (c_converter).
        CALL METHOD converter->(c_build)
          EXPORTING
            i_data = data
          IMPORTING
            e_data = result.
        ASSIGN converter->(c_hierarchy) TO <hierarchy>.
      CATCH cx_root INTO DATA(error).
        client->message_box_display( |Report ZJSON2ABAPTYPE (LCL_JSON_STRUCTURE) failed: { error->get_text( ) }| ).
        RETURN.
    ENDTRY.

    DATA hierarchy TYPE ty_t_hierarchy.
    IF <hierarchy> IS ASSIGNED.
      LOOP AT <hierarchy> ASSIGNING FIELD-SYMBOL(<row>).
        APPEND INITIAL LINE TO hierarchy ASSIGNING FIELD-SYMBOL(<line>).
        MOVE-CORRESPONDING <row> TO <line>.
      ENDLOOP.
    ENDIF.
    nodes_set( hierarchy ).

    types = COND #( WHEN pretty_print = abap_true THEN pretty_printer( result ) ELSE result ).

  ENDMETHOD.


  METHOD pretty_mode.

    result = SWITCH #( naming
                       WHEN `NONE`           THEN zui2_json=>pretty_mode-none
                       WHEN `LOW_CASE`       THEN zui2_json=>pretty_mode-low_case
                       WHEN `CAMEL_CASE`     THEN zui2_json=>pretty_mode-camel_case
                       WHEN `USER`           THEN zui2_json=>pretty_mode-user
                       WHEN `USER_LOW_CASE`  THEN zui2_json=>pretty_mode-user_low_case
                       WHEN `CASE_SENSITIVE` THEN zui2_json=>pretty_mode-case_sensitive
                       ELSE zui2_json=>pretty_mode-extended ).

  ENDMETHOD.


  METHOD name_mappings.

    LOOP AT t_mappings INTO DATA(mapping) WHERE json IS NOT INITIAL AND abap IS NOT INITIAL.
      " hashed by the ABAP name: a second mapping onto the same name is ignored
      INSERT VALUE #( abap = to_upper( mapping-abap ) json = mapping-json ) INTO TABLE result.
    ENDLOOP.

  ENDMETHOD.


  METHOD nodes_set.

    DATA(rows) = hierarchy.
    SORT rows BY level id.

    DATA(structures) = 0.
    DATA(tables) = 0.
    DATA(components) = 0.
    LOOP AT rows INTO DATA(row).
      APPEND INITIAL LINE TO t_nodes ASSIGNING FIELD-SYMBOL(<node>).
      <node>-level     = row-level.
      <node>-name      = row-name.
      <node>-type_kind = row-type.
      <node>-component = row-final_type.
      IF row-table = abap_true.
        <node>-kind  = `Table type`.
        <node>-state = `Warning`.
        tables = tables + 1.
      ELSEIF row-structure = abap_true.
        <node>-kind  = `Structure`.
        <node>-state = `Success`.
        structures = structures + 1.
      ELSE.
        <node>-kind  = `Component`.
        <node>-state = `None`.
        components = components + 1.
      ENDIF.
    ENDLOOP.

    summary = |{ structures } structures, { tables } table types and { components } elementary components detected. |
           && |Fields with an initial value (null, "", 0, false) are skipped by the library.|.

  ENDMETHOD.


  METHOD pretty_printer.

    DATA source TYPE ty_t_source.
    SPLIT val AT cl_abap_char_utilities=>newline INTO TABLE source.

    CALL FUNCTION 'PRETTY_PRINTER'
      EXPORTING
        inctoo             = abap_false
      TABLES
        ntext              = source
        otext              = source
      EXCEPTIONS
        enqueue_table_full = 1
        include_enqueued   = 2
        include_readerror  = 3
        include_writeerror = 4
        OTHERS             = 5.
    IF sy-subrc <> 0.
      result = val.
      RETURN.
    ENDIF.

    LOOP AT source INTO DATA(line).
      " a c field loses its trailing blanks in the concatenation, the indent stays
      result = result && line-line && cl_abap_char_utilities=>newline.
    ENDLOOP.

  ENDMETHOD.

ENDCLASS.
